spring.application.name=WebRomaPedidos

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:1433;databaseName=RomaDB1;encrypt=false;trustServerCertificate=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:mi_usuario}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:MiPasswordSeguro123!}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.microsoft.sqlserver.jdbc.SQLServerDriver}

spring.sql.init.mode=never

app.jwt.secret=${APP_JWT_SECRET:licoreria-roma-dev-secret-licoreria-roma-dev-secret}
app.jwt.expiration-minutes=${APP_JWT_EXPIRATION_MINUTES:1440}

server.port=${SERVER_PORT:8080}
